#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_hex.py —— 把可引导 ELF 转成纯 RTL testbench 用的 $readmemh 镜像。

不依赖任何 RISC-V 工具链:直接解析 ELF32 的 Program Header(PT_LOAD 段)。
输出是「字(32-bit)寻址」的 hex 文件,地址相对 MEM_BAS(默认 0x80000000),
配合 tb_top.v 里的  reg [31:0] mem [0:MEM_WORDS-1];  $readmemh 加载。

用法:
    python3 make_hex.py <input.elf> <output.hex> [mem_base_hex]
例:
    python3 make_hex.py ../../image/biriscv-linux-5.4.elf image.hex 0x80000000
"""
import sys, struct

def load_segments(path):
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"\x7fELF":
        sys.exit("不是 ELF 文件")
    ei_class = data[4]          # 1=32bit 2=64bit
    ei_data  = data[5]          # 1=LE 2=BE
    if ei_class != 1:
        sys.exit("只支持 ELF32(本镜像是 RV32)")
    end = "<" if ei_data == 1 else ">"
    # ELF32 header
    (e_phoff,) = struct.unpack_from(end + "I", data, 0x1C)
    (e_phentsize, e_phnum) = struct.unpack_from(end + "HH", data, 0x2A)
    segs = []
    for i in range(e_phnum):
        off = e_phoff + i * e_phentsize
        p_type, p_offset, p_vaddr, p_paddr, p_filesz, p_memsz, p_flags, p_align = \
            struct.unpack_from(end + "IIIIIIII", data, off)
        if p_type == 1 and p_filesz > 0:        # PT_LOAD with file content
            segs.append((p_paddr, data[p_offset:p_offset + p_filesz]))
    if not segs:
        sys.exit("没有可加载的 PT_LOAD 段")
    return segs

def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    elf, out = sys.argv[1], sys.argv[2]
    base = int(sys.argv[3], 0) if len(sys.argv) > 3 else 0x80000000

    segs = load_segments(elf)

    # 铺进一个 word 字典:word_index -> 32bit value(小端组字节)
    words = {}
    lo = hi = None
    for paddr, blob in segs:
        for i, b in enumerate(blob):
            addr = paddr + i
            if addr < base:
                continue
            widx = (addr - base) >> 2
            lane = (addr - base) & 3
            words[widx] = (words.get(widx, 0) | (b << (lane * 8))) & 0xFFFFFFFF
            lo = widx if lo is None else min(lo, widx)
            hi = widx if hi is None else max(hi, widx)

    # 以连续段的形式写出(@起始 + 连续的字),节省体积
    with open(out, "w") as f:
        f.write("// auto-generated by make_hex.py from %s\n" % elf)
        f.write("// word-addressed, base=0x%08x, words=%d..%d\n" % (base, lo, hi))
        idx = lo
        run_open = False
        for widx in range(lo, hi + 1):
            if widx in words:
                if not run_open:
                    f.write("@%x\n" % widx)
                    run_open = True
                f.write("%08x\n" % words[widx])
            else:
                run_open = False
    total = (hi - lo + 1)
    print("OK: %s  段=%d  非零字=%d  覆盖 0x%08x-0x%08x (%d KB)" %
          (out, len(segs), len(words), base + lo*4, base + hi*4 + 3, total*4//1024))

if __name__ == "__main__":
    main()
